apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: triage
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/lichenglin/kubectl-triage/releases/download/v0.1.0/kubectl-triage_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./kubectl-triage"
      to: "."
    - from: LICENSE
      to: "."
    bin: "kubectl-triage"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/lichenglin/kubectl-triage/releases/download/v0.1.0/kubectl-triage_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./kubectl-triage"
      to: "."
    - from: LICENSE
      to: "."
    bin: "kubectl-triage"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/lichenglin/kubectl-triage/releases/download/v0.1.0/kubectl-triage_windows_amd64.zip
    sha256: ""
    files:
    - from: "/kubectl-triage.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "kubectl-triage.exe"
  shortDescription: Fast triage for failed Kubernetes pods
  homepage: https://github.com/lichenglin/kubectl-triage
  caveats: |
    Usage:
      $ kubectl triage <pod-name>

    For additional options:
      $ kubectl triage --help
      or https://github.com/lichenglin/kubectl-triage/blob/v0.1.0/doc/USAGE.md

  description: |
    kubectl-triage provides a 5-second diagnostic snapshot for failed Kubernetes pods.
    It intelligently aggregates pod status, critical events, and container logs into a single view.
