apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: triage
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/Lc-Lin/kubectl-triage/releases/download/v0.1.0/kubectl-triage_linux_amd64.tar.gz
    sha256: "564f7a669a0055c37c1571f38cff6be631158fc06ee3902c36c52bf0739d19e6"
    files:
    - from: "./kubectl-triage"
      to: "."
    - from: LICENSE
      to: "."
    bin: "kubectl-triage"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/Lc-Lin/kubectl-triage/releases/download/v0.1.0/kubectl-triage_darwin_amd64.tar.gz
    sha256: "83fdcfe2f445ed6a5383add8ab8b5f2daeee2607b26828e335f99419a750a65e"
    files:
    - from: "./kubectl-triage"
      to: "."
    - from: LICENSE
      to: "."
    bin: "kubectl-triage"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/Lc-Lin/kubectl-triage/releases/download/v0.1.0/kubectl-triage_windows_amd64.zip
    sha256: "b5120c2a7fae43a2e76845a0b32b62a90ca2b949df590b564f664bc48e34fcf7"
    files:
    - from: "/kubectl-triage.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "kubectl-triage.exe"
  shortDescription: Fast triage for failed Kubernetes pods
  homepage: https://github.com/Lc-Lin/kubectl-triage
  caveats: |
    Usage:
      $ kubectl triage <pod-name>

    For additional options:
      $ kubectl triage --help
      or https://github.com/Lc-Lin/kubectl-triage/blob/v0.1.0/doc/USAGE.md

  description: |
    kubectl-triage provides a 5-second diagnostic snapshot for failed Kubernetes pods.
    It intelligently aggregates pod status, critical events, and container logs into a single view.
